MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'inception'
        PRETRAINED: True
        OUT_CHANNELS: [192, 288, 768, 768, 1280, 2048, 2048] # TODO adapt this
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [35, 35, 17, 17, 8, 8, 1] # TODO adapt this as well
        STRIDES: [8, 8, 17, 17, 37, 37, 299] # TODO adapt 
        MIN_SIZES: [30, 60, 111, 162, 213, 264, 315]
        MAX_SIZES: [60, 111, 162, 213, 264, 315, 366]
        ASPECT_RATIOS : [[2], [2, 3], [2, 3], [2, 3], [2], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4, 4]
INPUT:
    IMAGE_SIZE: 299
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/inception'
DATASET_DIR: "datasets"