MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'inception'
        PRETRAINED: True
        OUT_CHANNELS: [480, 512, 832, 1024, 1024] # TODO adapt this
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [37, 18, 18, 9, 1] # TODO adapt this as well
INPUT:
    IMAGE_SIZE: 299
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
OUTPUT_DIR: 'outputs/inception'
DATASET_DIR: "datasets"