MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'mixed'
        PRETRAINED: True
        # For resnet50
        OUT_CHANNELS: [512, 1024, 2048, 2048,   1024, 512, 256]
        # For resnet34 
        #OUT_CHANNELS: [128, 256, 512, 512,     256, 256, 256]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[40, 40], [20, 20], [10, 10], [1, 1],                      [5, 5], [3, 3], [1, 1]]
        STRIDES: [[8,8], [15, 15], [30, 30], [300, 300],               [60, 60], [100, 100], [300, 300]]
        MIN_SIZES: [[30, 30], [60, 60], [111, 111], [265, 265],      [163, 163], [213, 213], [265, 265]]
        MAX_SIZES: [[60, 60], [111, 111], [163, 163], [315, 315],    [213, 213], [265, 265], [315, 315]] # [WIDTH, HEIGHT]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2],                                      [2, 3], [2], [2]]
        BOXES_PER_LOCATION:                          [4, 6, 6, 4,                                6, 4, 4]
        #assumed that for the highest resolution the max size (for width) is 315/300 * width
        #and min_size is 264/300 * width
INPUT:
    IMAGE_WIDTH: 320
    IMAGE_HEIGHT: 240
    PIXEL_MEAN: [92, 101, 114]
    PIXEL_STD: [56,  62, 73]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
DATA_LOADER:
  NUM_WORKERS: 8
SOLVER:
    MAX_ITER: 320000
    LR_STEPS: [120000, 140000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
EVAL_STEP: 1000
MODEL_SAVE_STEP: 2000
OUTPUT_DIR: 'outputs/resnet50_320x240_imp_priors'
DATASET_DIR: "datasets"