MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet50'
        PRETRAINED: True
        OUT_CHANNELS: [512, 1024, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[30, 40], [15, 20], [8, 10], [4, 5], [2, 3], [1, 2]]
INPUT:
    IMAGE_WIDTH: 320 
    IMAGE_HEIGHT: 240
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
DATA_LOADER:
  NUM_WORKERS: 4
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
EVAL_STEP: 1000
MODEL_SAVE_STEP: 2500
OUTPUT_DIR: 'outputs/resnet50_320x240'
DATASET_DIR: "datasets"