MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet101'
        PRETRAINED: True
        OUT_CHANNELS: [512, 1024, 1024, 1024, 1024, 1024]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[30, 40], [15, 20], [8, 10], [4, 5], [2, 3], [1, 1]]
        STRIDES: [[8,8], [16, 16], [30, 32], [60, 64], [120, 106], [240, 320]]
INPUT:
    IMAGE_WIDTH: 320
    IMAGE_HEIGHT: 240
    PIXEL_MEAN: [92, 101, 114]
    PIXEL_STD: [56,  62, 73]
DATASETS:
    TRAIN: ("tdt4265_train",)
    TEST: ("tdt4265_val", )
DATA_LOADER:
  NUM_WORKERS: 4
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
EVAL_STEP: 2500
MODEL_SAVE_STEP: 2500
OUTPUT_DIR: outputs/resnet101_320x240_tdt4265
DATASET_DIR: "datasets"