MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet'
        PRETRAINED: True
        #TODO: check whether output fetures are correct for resnet 34
        OUT_CHANNELS: [512, 1024, 1024, 1024, 2048, 2048]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[40,30], [20, 15], [20,15], [20,15], [10,8], [1,1]]
        # strides should be image size/feature_map
        STRIDES: [[8,8], [16,16], [16,16], [16,16], [32,30], [320, 240]]
INPUT:
    IMAGE_SIZE: [320, 240]
#     PRIORS:
#         FEATURE_MAPS: [[45,34], [23, 17], [23,17], [23,17], [12,9], [1,1]]
#         # strides should be image size/feature_map
#         STRIDES: [[8,8], [16,16], [16,16], [16,16], [30,30], [360, 270]]
# INPUT:
#     IMAGE_SIZE: [360, 270]
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 5e-3
OUTPUT_DIR: 'outputs/resnet'
DATASET_DIR: "datasets"