MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet152'
        PRETRAINED: True
        OUT_CHANNELS:  [512, 1024, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
    PRIORS:
    #TODO: change last one to [1,1]
        FEATURE_MAPS: [[34, 45], [17, 23], [9, 12], [5, 6], [3, 3], [2, 2]]
        
INPUT:
    IMAGE_WIDTH: 360 
    IMAGE_HEIGHT: 270
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
DATA_LOADER:
  NUM_WORKERS: 8
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 5e-3
EVAL_STEP: 5000
MODEL_SAVE_STEP: 2500
OUTPUT_DIR: 'outputs/resnet152_360x270'
DATASET_DIR: "datasets"