MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet101'
        PRETRAINED: True
        OUT_CHANNELS: [512, 2048, 512, 512, 512, 256]
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [38, 10, 5, 3, 2, 1]
INPUT:
    IMAGE_SIZE: 300
DATASETS:
    TRAIN: ("waymo_train",)
    TEST: ("waymo_val", )
DATA_LOADER:
  NUM_WORKERS: 4
SOLVER:
    MAX_ITER: 120000
    LR_STEPS: [80000, 100000]
    GAMMA: 0.1
    BATCH_SIZE: 16
    LR: 1e-3
EVAL_STEP: 2500
MODEL_SAVE_STEP: 2500
OUTPUT_DIR: 'outputs/resnet101'
DATASET_DIR: "datasets"